myblog:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: myblog
    username: root
    password: 1234

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  rabbitmq:
    host: 192.168.209.130
    port: 5672
    virtual-host: /myblog
    username: myblog
    password: 123